### PR TITLE
Refactor into named call control functions

### PR DESCRIPTION
**Pull request by SuaYoo**
Refactors call control handler in `CallsController` by breaking into named functions for readability. Check out the [whole file](https://github.com/team-telnyx/telnyx-client-examples/blob/c12d60d275d4f053729c0727305b68e917f0e408/call-center/server/controllers/calls.controller.ts) to ensure readability.

## ✋ Manual testing

Run `npm test` in call-center/server. All tests should pass

### Desktop
- [ ] Edge
- [x] Chrome
- [ ] Firefox
- [ ] Safari

### Mobile
- [ ] Chrome (Android)
- [ ] Safari (iOS)

## 📸 Screenshots

### CODE REVIEW

**Review by DeividVeloso — APPROVED** [review]

**Review by DeividVeloso — CHANGES_REQUESTED** [review]
I tested and I tried to do an outbound and an inbound call but both failed

Inbound Error:
The audio plays the music alerting that I have a call, but on the front end it is not showing the screen with a button to answer the call.


Outbound error:
image

**Comment by SuaYoo** [comment]
@DeividVeloso , I'm able to successfully place inbound and outbound calls on this branch on Chrome, incognito mode.

I see in your first screenshot that the error states your number needs to be in E164 format (we don't do any formatting for the user right now in this app.) Could you try testing again?

**Comment by SuaYoo** [comment]
@DeividVeloso, I'm able to consistently receive and make calls using Chrome (incognito.) However, I've made improvements on error handling based on your screenshots. Could you pull and try manual testing again?

**Comment by hugobdev** [comment]
@DeividVeloso @SuaYoo I was also able to get outbound and inbound calls working.
image

**Comment by DeividVeloso** [comment]
@SuaYoo and @hugobdev I did an inbound and an outbound call and it is working.

I got a strange behavior when I did an outbound call I can **not** hear the voices and the remove call buttons they disappear.

image

**Review by DeividVeloso — APPROVED** [review]

**Pull request merged**
